server:
  port: 8081

spring:
  application:
    name: chat-gateway-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: websocket-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer