server:
  port: 8081

gateway:
  instance-id: gateway-1

spring:
  data:
    redis:
      host: localhost
      port: 6379    
  
  application:
    name: chat-gateway-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: websocket-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer